### ISSUE TITLE
v1.0 Roadmap and beyond

### ISSUE THREAD

**Issue by WillNilges** [WillNilges/inkpath#10]
## v0.2
- [ ] Expose knobs, dials, and sliders to user to improve scaling and placement of strokes on the canvas.
- [ ] Pull in code from #5 

## v1.0
- [x] Add options for tweaking line thickness/bezier precision?
- [ ] [Add save detection](https://github.com/xournalpp/xournalpp/issues/2850#issuecomment-950343642)
- [ ] Loading dialog
    - [ ] Don't block when transcribing?
- [x] Skirt bezierCurve math and pass splines directly to Xournalpp
- [ ] Further optimize data transfer code

## v1.1 
- [ ] Preprocessing
- [ ] Fix broken file formats (Such as JPEG and BMP)

## v1.2
- [ ] Add color support

## v1.3
- [ ] Multithread autotrace and/or spline parsing
- [ ] Additional contributions to Autotrace

**Comment by WillNilges** [comment]
Notes of things that don't work:
- Skeletonization. There's just a lot wrong with it. It behaves in strange and unexpected ways.

**Comment by WillNilges** [comment]
Well, we could probably get that working, actually, but one thing at a time!!!!
